- name: Configuring the {{COMPONENT}} repo
  ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongodb.repo
    
- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Configuring the {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Download and extracting the frontend
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Starting {{COMPONENT}}
  systemd:
    name: mongod
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Confuguring Service name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}

