- name: play1
  hosts: all
  tasks: 
  - name: Print Hai from task1 of play1
    ansible.builtin.debug:
      msg: "Hai from task1 of play1"
  
  - name: Print Hai from task1 of play1
    ansible.builtin.debug:
      msg: "Devops batch55 of play1"    
