- name: Demo on facts
  hosts: all
  tasks: 
  - name: Printing the default variable
    ansible.builtin.debug:
     msg: Server flaver is "{{ansible_distribution}}"

  - name: Printing the mac address
    ansible.builtin.debug:
      msg: Mac Address Of The Node Is "{{ansible_default_ipv4.macaddress}}"     