- name: Demo on previllege escalltion
  hosts: all
  tasks: 
  - name: Check the User ID
    ansible.builtin.shell: id
    register: OUT
  
  - name: Printing the user details
    ansible.builtin.debug
      msg: "{{OUT}}"
    