- name: Demo on installing package
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present



#- name: Install ntpdate
  #ansible.builtin.package:
    #name: ntpdate
    #state: present