
- name: Demo on copy file
  hosts: all
  become: yes
  tasks:
    - name: Copying the  file 
      ansible.builtin.copy:
        src: systemd.service 
        dest: /home/centos/systemd.service


- name: Copying the proxy file
  ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

- name: Starting Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes