- name: Installing python
  ansible.builtin.package:
    name: 
      - python36 
      - gcc 
      - python3-devel
    state: present

- name: Creating the App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and Extracing the {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Updating the Uid of {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{USERINFO.uid}}

- name: Updating the Gid of {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{USERINFO.gid}}



